"""
visualize_results.py
Generate validation & overview figures for the CO2‑to‑SAF digital twin.
No training – only loads existing data, models, and GAN generators.
"""
import pandas as pd
import numpy as np
import joblib
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from sklearn.metrics import r2_score, mean_absolute_error

from config import DATA_DIR, PROC_DIR, RESULT_DIR

# ── Matplotlib style ────────────────────────────────────────────────────────
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette("husl")
FIG_DIR = RESULT_DIR / "figures"
FIG_DIR.mkdir(parents=True, exist_ok=True)

# =============================================================================
# 1. Load data
# =============================================================================
blended = pd.read_csv(DATA_DIR / "blended_plant_runs.csv")    # real + synthetic
pool = pd.read_csv(PROC_DIR / "oracle_pool.csv")             # oracle predictions
desc = pd.read_csv(PROC_DIR / "catalyst_descriptors.csv")
desc["facet"] = desc["facet"].astype(str)
blended["facet"] = blended["facet"].astype(str)

# Shanghai pilot reference point (from your config)
ref_point = {"STY_mg_gcat_h": 252.7, "SAF_selectivity": 0.375,
             "temperature_K": 603, "pressure_bar": 20, "promoter": "K", "facet": "110"}

# =============================================================================
# 2. Parity plot – Oracle vs. Plant Model on synthetic data
# =============================================================================
# The blended file contains synthetic data generated by the plant model.
# We'll compare the oracle's predictions on that same data (using the oracle pool or re-predict).
# For a clean parity plot, use the pool (oracle predictions) vs. original synthetic STY.
synth = pd.read_csv(PROC_DIR / "synthetic_plant_runs.csv")
synth["facet"] = synth["facet"].astype(str)

# We need oracle predictions for the synthetic dataset.
# Load oracle
bundle = joblib.load("oracle.pkl")
model_sty = bundle["model_sty"]
model_sel = bundle["model_sel"]
scaler_oracle = bundle["scaler"]
feat_cols = bundle["feature_cols"]

# Prepare features for synthetic runs (merge descriptors)
merged_synth = synth.merge(desc, on=["facet","promoter"], how="left")
X_synth = merged_synth[feat_cols].fillna(0)
X_synth_sc = scaler_oracle.transform(X_synth)
pred_log_sty = model_sty.predict(X_synth_sc)
pred_sty = 10**pred_log_sty * 1000   # mg/g/h
pred_sel = model_sel.predict(X_synth_sc)
true_sty = synth["STY_mg_gcat_h"].values
true_sel = synth["SAF_selectivity"].values

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
axes[0].scatter(true_sty, pred_sty, alpha=0.1, s=1)
axes[0].plot([0, 400], [0, 400], 'k--')
axes[0].set_xlabel("Plant model STY (mg/g/h)")
axes[0].set_ylabel("Oracle predicted STY (mg/g/h)")
axes[0].set_title(f"STY Parity (R²={r2_score(true_sty, pred_sty):.3f}, MAE={mean_absolute_error(true_sty, pred_sty):.1f})")

axes[1].scatter(true_sel, pred_sel, alpha=0.1, s=1)
axes[1].plot([0.1, 0.5], [0.1, 0.5], 'k--')
axes[1].set_xlabel("Plant model selectivity")
axes[1].set_ylabel("Oracle predicted selectivity")
axes[1].set_title(f"Selectivity Parity (R²={r2_score(true_sel, pred_sel):.3f}, MAE={mean_absolute_error(true_sel, pred_sel):.3f})")
plt.tight_layout()
plt.savefig(FIG_DIR / "parity_oracle_vs_plant.png", dpi=150)
plt.close()
print("Parity plot saved.")

# =============================================================================
# 3. Temperature and pressure effects per promoter
# =============================================================================
# We'll use the synthetic dataset (which has full factorial design).
# Filter to a specific facet (e.g., 110) and show STY/selectivity vs T for each promoter.
facet_sel = "110"
df_f = synth[synth["facet"] == facet_sel]

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
# STY vs T
for prom in ["none","K","Re","Ru","Pt"]:
    sub = df_f[df_f["promoter"]==prom]
    axes[0,0].plot(sub["temperature_K"], sub["STY_mg_gcat_h"], alpha=0.6, lw=1, label=prom)
axes[0,0].set_xlabel("Temperature (K)")
axes[0,0].set_ylabel("STY (mg/g/h)")
axes[0,0].legend(title="Promoter")
axes[0,0].set_title(f"STY vs Temperature (Facet {facet_sel})")

# Selectivity vs T
for prom in ["none","K","Re","Ru","Pt"]:
    sub = df_f[df_f["promoter"]==prom]
    axes[0,1].plot(sub["temperature_K"], sub["SAF_selectivity"], alpha=0.6, lw=1, label=prom)
axes[0,1].set_xlabel("Temperature (K)")
axes[0,1].set_ylabel("SAF selectivity")
axes[0,1].legend(title="Promoter")
axes[0,1].set_title(f"Selectivity vs Temperature (Facet {facet_sel})")

# STY vs P (at a fixed T, e.g., 550 K)
T_fixed = 550
sub_T = df_f[df_f["temperature_K"]==T_fixed]
for prom in ["none","K","Re","Ru","Pt"]:
    sub = sub_T[sub_T["promoter"]==prom]
    axes[1,0].plot(sub["pressure_bar"], sub["STY_mg_gcat_h"], alpha=0.6, lw=1, label=prom)
axes[1,0].set_xlabel("Pressure (bar)")
axes[1,0].set_ylabel("STY (mg/g/h)")
axes[1,0].legend(title="Promoter")
axes[1,0].set_title(f"STY vs Pressure at T={T_fixed} K")

# Selectivity vs P
for prom in ["none","K","Re","Ru","Pt"]:
    sub = sub_T[sub_T["promoter"]==prom]
    axes[1,1].plot(sub["pressure_bar"], sub["SAF_selectivity"], alpha=0.6, lw=1, label=prom)
axes[1,1].set_xlabel("Pressure (bar)")
axes[1,1].set_ylabel("SAF selectivity")
axes[1,1].legend(title="Promoter")
axes[1,1].set_title(f"Selectivity vs Pressure at T={T_fixed} K")
plt.tight_layout()
plt.savefig(FIG_DIR / "promoter_effects.png", dpi=150)
plt.close()
print("Promoter effect plots saved.")

# =============================================================================
# 4. Active learning convergence (best score over iterations)
# =============================================================================
# We didn't log history, but we can show the final best score vs initial best.
# Since we can't retrieve the curve, we'll create a bar chart: initial best vs final best.
# If you still have the active learning output, you could parse it. Here we hardcode from the print you gave.
initial_best = 94.76   # reference score
final_best = pool["score"].max()
fig, ax = plt.subplots(figsize=(5,4))
ax.bar(["Initial (prior)", "After Active Learning"], [initial_best, final_best], color=['gray','orange'])
ax.set_ylabel("Best product score (STY * selectivity)")
ax.set_title("Active learning improvement")
for i, v in enumerate([initial_best, final_best]):
    ax.text(i, v+2, f"{v:.1f}", ha='center')
plt.tight_layout()
plt.savefig(FIG_DIR / "active_learning_improvement.png", dpi=150)
plt.close()
print("Active learning improvement saved.")

# =============================================================================
# 5. GAN candidate scatter plot
# =============================================================================
# Use the GAN-generated candidates (scored) from pool? Actually pool contains oracle evaluated grid,
# but we have GAN-specific samples from earlier output. We'll generate new GAN samples and score them.
# Load GAN generators (standalone classes as in score_candidates.py)
class ProcessGenerator(nn.Module):
    def __init__(self, latent_dim=16, input_dim=2):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(latent_dim + 1, 128), nn.BatchNorm1d(128), nn.LeakyReLU(0.2),
            nn.Linear(128, 128), nn.BatchNorm1d(128), nn.LeakyReLU(0.2),
            nn.Linear(128, input_dim),
        )
    def forward(self, z, c):
        return self.net(torch.cat([z, c], dim=1))

class CatalystGenerator(nn.Module):
    def __init__(self, latent_dim=64, cont_dim=6, n_facets=3, n_proms=8):
        super().__init__()
        self.shared = nn.Sequential(
            nn.Linear(latent_dim + 1, 256), nn.BatchNorm1d(256), nn.LeakyReLU(0.2),
            nn.Linear(256, 256), nn.BatchNorm1d(256), nn.LeakyReLU(0.2),
        )
        self.cont_out  = nn.Linear(256, cont_dim)
        self.facet_out = nn.Linear(256, n_facets)
        self.prom_out  = nn.Linear(256, n_proms)
    def forward(self, z, c):
        h = self.shared(torch.cat([z, c], dim=1))
        return self.cont_out(h), self.facet_out(h), self.prom_out(h)

facet_le, prom_le = joblib.load("catalyst_encoders.pkl")
cont_scaler = joblib.load("catalyst_scaler.pkl")
G_cat = CatalystGenerator(64, 6, len(facet_le.classes_), len(prom_le.classes_))
G_cat.load_state_dict(torch.load("catalyst_gan_g.pth", map_location="cpu"))
G_cat.eval()

proc_scaler = joblib.load("process_scaler.pkl")
G_proc = ProcessGenerator(16, 2)
G_proc.load_state_dict(torch.load("process_gan_g.pth", map_location="cpu"))
G_proc.eval()

N = 2000
z_cat = torch.randn(N, 64)
c_cat = torch.ones(N, 1)
with torch.no_grad():
    cont_norm, fl, pl = G_cat(z_cat, c_cat)
    cont = cont_scaler.inverse_transform(cont_norm.numpy())
    facets = facet_le.inverse_transform(fl.argmax(1).numpy())
    proms  = prom_le.inverse_transform(pl.argmax(1).numpy())
z_proc = torch.randn(N, 16)
c_proc = torch.ones(N, 1)
with torch.no_grad():
    proc_norm = G_proc(z_proc, c_proc).numpy()
proc = proc_scaler.inverse_transform(proc_norm)

rows = []
for i in range(N):
    f, p = str(facets[i]), str(proms[i])
    cat_row = desc[(desc.facet == f) & (desc.promoter == p)]
    if cat_row.empty:
        continue
    T, P = proc[i,0], proc[i,1]
    if P < 1 or P > 40:
        continue
    feat = {}
    for col in feat_cols:
        if col in cat_row.columns:
            feat[col] = cat_row.iloc[0][col]
        elif col == "temperature_K":
            feat[col] = T
        elif col == "pressure_bar":
            feat[col] = P
    vec = np.array([feat[col] for col in feat_cols]).reshape(1,-1)
    vec_sc = scaler_oracle.transform(vec)
    log_sty = model_sty.predict(vec_sc)[0]
    sel = model_sel.predict(vec_sc)[0]
    sty_mg = 10**log_sty * 1000
    rows.append((f, p, T, P, sty_mg, sel))
df_gan = pd.DataFrame(rows, columns=["facet","promoter","T_K","P_bar","STY_mg_gcat_h","SAF_selectivity"])

# Scatter: STY vs selectivity, colored by promoter
fig, ax = plt.subplots(figsize=(8,6))
for prom in df_gan["promoter"].unique():
    sub = df_gan[df_gan["promoter"]==prom]
    ax.scatter(sub["STY_mg_gcat_h"], sub["SAF_selectivity"], s=10, alpha=0.5, label=prom)
# Mark reference point
ax.scatter(ref_point["STY_mg_gcat_h"], ref_point["SAF_selectivity"], c='red', marker='*', s=200, label='Shanghai Pilot')
ax.set_xlabel("STY (mg/g/h)")
ax.set_ylabel("SAF selectivity")
ax.legend()
ax.set_title("GAN-generated candidates")
plt.tight_layout()
plt.savefig(FIG_DIR / "gan_candidates.png", dpi=150)
plt.close()
print("GAN candidate plot saved.")

# =============================================================================
# 6. Summary of assumptions table (printed to console and saved as text)
# =============================================================================
assumptions = """
Digital Twin Assumptions:
1. Plant model uses constant single-pass CO conversion (0.51) with promoter-dependent multiplier.
2. Chain growth probability (alpha) varies linearly with temperature (base alpha=0.78, -0.0005/K) and promoter (0.01 per multiplier unit).
3. Selectivity is mass selectivity of C8-C16 paraffins.
4. Adsorption energies from CHGNet (universal ML potential) used as catalyst descriptors.
5. Oracle: Random Forest trained on blended synthetic + real plant data.
6. Active learning uses Expected Improvement on product score (STY * selectivity).
7. GANs are property-guided, conditioned on top-20% class, with gradient penalty.
"""
with open(FIG_DIR / "assumptions.txt", "w") as f:
    f.write(assumptions)
print(assumptions)
print(f"\nAll figures saved to {FIG_DIR}")
